bindsym $mod+b+Return exec brave
bindsym $mod+n+return exec kitty -e nvim

#kitty

# 1. Define behavior for the unique terminal
# This catches the terminal when it launches, floats it, sets a size, moves it to the scratchpad, and instantly shows it.
for_window [app_id="scratchpad-term"] floating enable, move position center, resize set height 700, resize set width 1200, move scratchpad, scratchpad show

# 2. Launch it manually
# Mod + Shift + T starts kitty with the unique app_id
bindsym $mod+Shift+t exec env IS_SCRATCHPAD=1 kitty --class scratchpad-term

# 3. Toggle it on and off
# Mod + T will bring it up or hide it, targeting only this specific instance
bindsym $mod+t [app_id="scratchpad-term"] scratchpad show

#mpv * youtube 

# Make our custom mpv window floating and sticky
for_window [title="^yt-float$"] floating enable, move position center, resize set height 700, resize set width 1200, move scratchpad, scratchpad show


# Play copied URL in floating mpv
bindsym $mod+y exec mpv --title="yt-float" "$(wl-paste)"

#Play copied URL with dgpu
bindsym $mod+Shift+y exec prime-run mpv --title="yt-float" "$(wl-paste)"
