# ~/.config/sway/config.d/theme.conf

# Font Settings
# Using Pango to ensure ligatures and icons render correctly
font pango:JetBrainsMono Nerd Font 11.5

# Status Bar
exec_always bash -c 'if pkill -x waybar; then sleep 0; waybar; else sleep 0.05; waybar; fi'

# Start nightlight automatically on boot
exec ~/.config/waybar/scripts/nightlight.sh on

# Border Settings
smart_borders on
default_border pixel 1
default_floating_border pixel 1

# Focus Colors (Normal Focus: Active window is highlighted)
# class                 border  bground text    indicator child_border
client.focused          #b8c0e0 #b8c0e0 #24273a #b8c0e0   #b8c0e0
client.focused_inactive #24273a #24273a #b8c0e0 #24273a   #24273a
client.unfocused        #24273a #24273a #b8c0e0 #24273a   #24273a
client.urgent           #ed8796 #ed8796 #24273a #ed8796   #ed8796

# Set the cursor for the Sway environment
seat seat0 xcursor_theme catppuccin-macchiato-dark-cursors 22

# Force Wayland/XWayland apps to inherit the theme
exec_always export XCURSOR_THEME=catppuccin-macchiato-dark-cursors
exec_always export XCURSOR_SIZE= 22
