# ~/.config/sway/config.d/theme.conf

# Font Settings
# Using Pango to ensure ligatures and icons render correctly
font pango:JetBrainsMono Nerd Font 11.5

# Status Bar
exec_always bash -c 'if pkill -x waybar; then sleep 0; waybar; else sleep 0.05; waybar; fi'

# Start nightlight automatically on boot
exec ~/.config/waybar/scripts/nightlight.sh on

# Border Settings
smart_borders on
smart_gaps on
default_border pixel 2
default_floating_border pixel 2
#gaps inner 10
#gaps outer 10

# Focus Colors (Normal Focus: Active window is highlighted)
# format:                 border  background text    indicator child_border
client.focused          #5c6b7b #5c6b7b    #ffffff #5c6b7b   #5c6b7b
client.focused_inactive #000000 #000000    #ffffff #000000   #000000
client.unfocused        #000000 #000000    #ffffff #000000   #000000
client.urgent           #eb4d4b #eb4d4b    #ffffff #eb4d4b   #eb4d4b
