[mgr]
prepend_keymap = [
    { on = "E", run = 'shell "footclient -e nvim \"$1\"" --confirm --orphan', desc = "Open Neovim in a new window" }
]

[manager]
prepend_keymap = [
    # Override Enter to open the file, then immediately quit Yazi
    { on = [ "<Enter>" ], run = [ "open", "quit" ], desc = "Open file and quit" }
]
