[opener]
edit = [
    { run = 'nvim %s', block = true, desc = "Neovim" }
]
zathura = [
    { run = 'zathura %s', orphan = true, desc = "Open with Zathura" }
]
terminal = [
    { run = 'alacritty --working-directory %s', orphan = true, desc = "Open terminal here" }
]

[open]
prepend_rules = [
    # Pressing Enter on a folder opens Alacritty in that path
    { mime = "inode/directory", use = "terminal" },
    # Fallback directory match just in case the MIME check fails
    { url = "*/", use = "terminal" },

    # Open PDFs with Zathura
    { mime = "application/pdf", use = "zathura" },

    # Catch MIME types first
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    
    # Use 'url' instead of 'name' for file extensions
    { url = "*.c", use = "edit" },
    { url = "*.cpp", use = "edit" },
    { url = "*.h", use = "edit" },
    { url = "*.md", use = "edit" }
]
