# ==========================================
# Global Ultra-Lightweight Settings
# ==========================================
profile=fast
vo=gpu
hwdec=auto-safe

# Force the most basic, cheapest scaling algorithms
scale=bilinear
cscale=bilinear
dscale=bilinear
tscale=oversample
dither-depth=no
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no
deband=no

# Cacheing to HDD
cache=yes                                                                                       
cache-on-disk=yes                                                                               
demuxer-cache-dir= /mnt/Acharya/MPV-CACHE/
