# ==========================================
# Default: AMD Integrated Graphics
# ==========================================
vo=gpu
gpu-api=opengl
hwdec=vaapi

# ==========================================
# Override: NVIDIA Discrete Graphics
# ==========================================
[nvidia]
profile-cond=os.getenv("__NV_PRIME_RENDER_OFFLOAD") == "1"
vo=gpu-next
gpu-api=vulkan
hwdec=nvdec
