return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'c',
      'rust',
      'cpp',
      'lua',
      'python',
      'vimdoc',
      'vim',
      'regex',
      'gitignore',
      'make',
      'cmake',
      'markdown',
      'markdown_inline',
      'bash',
      'css',
      'html',
      'java',
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
